---
abstract: 'no line insertion and does Package version with our'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-OurPkgVersion
requires:
  Carp: 0
  Moose: 0
  PPI: 0
  namespace::autoclean: 0
  perl: 5.010
resources:
  bugtracker: http://github.com/xenoterracide/Dist-Zilla-Plugin-OurPkgVersion/issues
  repository: git://github.com/xenoterracide/Dist-Zilla-Plugin-OurPkgVersion.git
version: 0.1.0
