---
abstract: 'no line insertion and does Package version with our'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::DZil: 0
  Test::More: 0.88
  Test::Requires: 0
  Test::Version: 0.04
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-OurPkgVersion
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
requires:
  Carp: 0
  Dist::Zilla::Role::FileFinderUser: 0
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  MooseX::Types::Perl: 0
  PPI: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/Dist-Zilla-Plugin-OurPkgVersion/issues
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-OurPkgVersion/
  repository: git://github.com/xenoterracide/Dist-Zilla-Plugin-OurPkgVersion.git
version: 0.003002
